Touch API
tock/libtock-c pull request #126
Opened 2020-12-11 16:15 UTC by alexandruradovici

The PR adds the user space API for the touch driver (https://github.com/tock/tock/pull/2060).

2020-12-14 20:41 UTC, phil-levis requested changes
This looks fine, but I'd like to either wait for 2.0 to settle down or have you apply this to the 2.0 branch.

2020-12-14 20:41 UTC, phil-levis commented on examples/lvgl/lvgl_driver.c
> +static void tocuh_event (int status, int x, int y, void *ud __attribute__ ((unused))) {
```suggestion
static void touch_event (int status, int x, int y, void *ud __attribute__ ((unused))) {
```

2020-12-22 19:11 UTC, alexandruradovici commented
Are you suggesting to apply this directly to Tock 2.0 with the new API?

2020-12-24 17:29 UTC, hudson-ayers commented
> Are you suggesting to apply this directly to Tock 2.0 using the new API?

Yes, I think so.

2021-03-22 20:20 UTC, closed without merging