Add cycle counter driver and test app
tock/libtock-c pull request #386
Opened 2024-04-01 05:53 UTC by hudson-ayers

This PR adds a driver for the cycle counter capsule, for which kernel support is being added in https://github.com/tock/tock/pull/3934. It also adds a basic test application which prints the number of cycles required to toggle an LED, after checking that the ability to start and stop the driver has not already been claimed by another app.

Tested by adding the capsule to the nrf52840dk and running this app. It takes about 4000 cycles to toggle an LED from userspace.

2024-04-02 00:36 UTC, alistair23 commented on libtock/cycle_counter.h
> +int cycle_counter_read(int *count);
It's probably best to document these in the header file.

It's also worth saying that stop does not reset the counter and it needs to manually be reset

2024-04-02 02:31 UTC, bradjc commented
Can I ask you follow the new guide? https://github.com/tock/libtock-c/blob/43525b8fedff3531685dbb20b08916addcca0997/doc/guide.md

Maybe not the syscalls folder but the naming convention?

2024-04-10 22:25 UTC, ppannuto approved these changes
Little ergonomic patch, but o/w looks good pending the kernel impl

2024-04-10 22:25 UTC, ppannuto commented on examples/tests/cycle_count/main.c
> +    printf("Cycle counter: other error: %d\n", rc);
```suggestion
    printf("Cycle counter: other error: %d (%s)\n", rc, tock_strerr(rc));
```

2024-04-15 20:31 UTC, bradjc requested changes
new libtock format

2024-04-24 02:55 UTC, hudson-ayers commented
I will come back to this once the new libtock format is merged

2024-10-02 17:03 UTC, ppannuto commented
@hudson-ayers is this still on your queue?

2024-10-07 02:17 UTC, hudson-ayers commented
> @hudson-ayers is this still on your queue?

Yeah it is, just have had limited time for Tock stuff and have focused more on kernel stuff. I will get back to this eventually

2025-09-05 20:37 UTC, ppannuto commented
Closing as stale with no prejudice.

2025-09-05 20:37 UTC, closed without merging