test: simple multi alarm test
tock/libtock-c pull request #466
Opened 2024-09-05 23:38 UTC by alevy

This adds an intentionally simple test for multiple alarms that only sets exactly two repeating alarms that should overlap frequently (one is twice the other's frequency). It sets two repeating alarms, at 500ms and 1s respectively, each prints the alarm index (1 or 2), current tick and alarm expiration to the console. When successful, both alarms should fire and alarm 1 should fire twice as often as alarm 2.

Today (on the NRF52840 at least, though I don't expect other chips to be different), this test fails. It should output (the first column in each line is the timer index):

```sh
1 6316032 6314240
2 10512384 10510592
1 10512384 10511104
1 14722560 14720768
2 18903552 18901760
1 18919680 18917632
1 23116544 23114752
2 27294720 27292928
...
```

but, due to a bug in the alarm library, actually outputs:

```sh
1 7254784 7252992
2 11451136 11449344
2 19842304 19840512
2 28233472 28231680
2 36624640 36622848
2 45015808 45014016
2 53406976 53405184
...
```

(note timer `1` never appears after the first instance)

I believe this is a regression in how alarms are added to the virtual alarm queue using the `within_range` functions. Follow up suggested fix to come hopefully soon.

2024-09-06 00:11 UTC, tyler-potyondy submitted a review, later dismissed
This is an interesting bug and perhaps explains some of the edge case bugs we've seen with the OpenThread library. 

I'm curious to see what the root cause ends up being.

2024-09-06 04:10 UTC, ppannuto commented on examples/tests/multi_alarm_simple_test/main.c
> +                     void*                             ud) {
```suggestion
static void event_cb(uint32_t now, uint32_t expiration, void* ud) {
```

I'm mildly annoyed that using an "unused"isn't some kind of warning...

2024-09-06 15:17 UTC, brghena approved these changes

2024-09-08 14:43 UTC, lschuermann commented
Good catch, and the test seems fine to me.

However, this does raise a more general issue to me, and one that relates to our releases, automated tests, and the timer subsystem in particular: how to assert whether the test ran correctly, or not.

In particular, for timer tests we often just produce some raw, unprocessed output. When it comes to running these tests as part of a release (esp. with our release cadence), we then need to re-learn what it means for these tests to pass or fail. Similarly, with automated tests, esp. with non-deterministic output, it can be hard to encode a check function that determines the test result.

We may want to take this opportunity to figure out what we can add to the user space tests and/or a test framework to make this easier.

2024-09-12 09:46 UTC, lschuermann commented
FWIW, @charles37 is working on an automated test for this, to be integrated into Treadmill.

2024-09-14 04:34 UTC, alevy commented
A significant update that adds another test (for clock overflow) and (I believe) fixes the underlying issue. See new PR description.

2024-09-19 04:11 UTC, brghena commented
I will look over this tomorrow. Thanks for the nudge.

2024-09-19 18:02 UTC, tyler-potyondy requested changes
The logic for the timer placement seems to check out and is an improvement over the somewhat opaque within range function. I have one small comment for improving the readability of the logic, but overall the changes look good to me.

2024-09-19 21:14 UTC, brghena requested changes
This is a good catch and the fix looks good to me. I have a bunch of small things to clean up though.

2024-09-19 21:14 UTC, brghena commented on libtock/services/alarm.c
> +    // This alarm happens after the new alarm if:
What is "this alarm" and what is "the new alarm"? I think it's `cur` and `alarm` respectively? But I might have that backwards. In my opinion, this entire comment block should use the actual names for clarity.

2024-09-19 21:14 UTC, brghena commented on libtock/services/alarm.c
> +    if (!(!cur_overflows && new_overflows) && ((cur_overflows && !new_overflows) || cur_expiration > new_expiration)) {
I strongly agree. I really can't parse line 110.

Based on my reading of the comment, the logic would be `if ((cur_overflows && !new_overflows) || (cur_expiration > new_expiration))`. I don't understand why the first part of the condition is there.

2024-09-19 21:14 UTC, brghena commented on examples/tests/multi_alarm_simple_overflow_test/README.md
> +alarms, first one that overflows the alarm, such that it's expiration
```suggestion
alarms, first one that overflows the alarm, such that its expiration
```

2024-09-19 21:14 UTC, brghena commented on examples/tests/multi_alarm_simple_overflow_test/README.md
> +is small in absolute value (but should shouldn't fire until after the
Should or shouldn't? Pick one please

2024-09-20 16:14 UTC, ppannuto requested changes
Review of everything except timer logic so far sorry

2024-09-20 18:07 UTC, alevy commented on examples/tests/multi_alarm_simple_test/README.md
> +often as alarm 2.
Done, see below

2024-09-20 18:16 UTC, alevy commented on libtock/services/alarm.c
> +    if (!(!cur_overflows && new_overflows) && ((cur_overflows && !new_overflows) || cur_expiration > new_expiration)) {
I couldn't quite help myself from being a tiny bit clever still, but I believe the new version of both the comment and boolean logic are clear now.

2024-09-20 18:24 UTC, alevy commented on examples/tests/multi_alarm_simple_overflow_test/README.md
> +it won't fire immediately.
See below

2024-09-20 18:24 UTC, alevy commented
@ppannuto @tyler-potyondy @brghena all comments addressed

2024-09-20 18:54 UTC, brghena submitted a review, later dismissed

2024-09-20 19:05 UTC, tyler-potyondy submitted a review, later dismissed

2024-09-23 22:31 UTC, ppannuto approved these changes

2024-09-23 22:47 UTC, merged