examples: enviro_sensor: Support a environment sensor example
tock/libtock-c pull request #475
Opened 2024-11-12 03:44 UTC by alistair23

Support the new moisture sensor and add a environment sensor example application

2024-11-13 19:04 UTC, ppannuto requested changes
Looks good to me, only blocking comment is the 'example output'.

---

Any reason to have a new app here instead of adding to the existing sensors app ( https://github.com/tock/libtock-c/tree/master/examples/sensors ) ?

2024-11-13 23:43 UTC, alistair23 commented
> Any reason to have a new app here instead of adding to the existing sensors app ( https://github.com/tock/libtock-c/tree/master/examples/sensors ) ?

Nope! I just didn't know that existed. I've switched to using that instead

2024-11-14 00:39 UTC, ppannuto submitted a review, later dismissed
lgtm; the 'example output' for sensors is a bit awkward, as we don't have any board with _all_ of the sensors I don't think, so I think leaving that unchanged here is fine

2024-11-18 23:23 UTC, ppannuto approved these changes

2024-11-18 23:34 UTC, merged